# Site settings
title: Kun's Blog
header-img: "img/elephant.jpg"
description: "Kun's blog"
baseurl: ""
url: "https://kaka2634.github.io"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "KunLiu"
  email: 996529090@qq.com

# Data
favicon: /img/favicon.png
avatar: /img/kun.png
github_username: kaka2634
weibo_username: 3509237361
zhihu_username: liukun-21

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge


#Jekyll plugins
#Jekyll sitemap： https://github.com/jekyll/jekyll-sitemap
#Jekyll feed: https://github.com/jekyll/jekyll-feed
#sitemap.xml and feed.xml will generate on _site
plugins:
#- jekyll-gallery-generator
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","googlea2a23e8dd40b1961.html", "baidu_verify_oGiFGUmzfC.html"]

#Timezone
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Comments 
# gittalk
gitalk:
   enable: true
   owner: kaka2634
   repo: kaka2634.github.io
   clientID: 6bb1012855494cd52cf1
   clientSecret: a9826856075b6f68f11033a68bc9a793fd27f736
   admin: kaka2634

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "KunLiu"
      header-img: "img/mountain.jpg" # We don't want posts without a header image, that whould mean white on white


# Analytics and webmaster tools stuff goes here
google_analytics: UA-87821158-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

